---
# roles/serveur/tasks/main.yml

- name: Install Apache and PHP
  apt:
    name:
      - apache2
      - php
      - libapache2-mod-php
      - php-mysql
    state: present
    update_cache: yes

- name: Start and enable Apache service
  service:
    name: apache2
    state: started
    enabled: yes

- name: relancer Apache
  service:
    name: apache2
    state: restarted
